// <auto-generated />
using System;
using Book_Store.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Book_Store.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Book_Store.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("dateOfBirth")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "",
                            Name = "John",
                            dateOfBirth = new DateTime(2000, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Bio = "",
                            Name = "Arnold",
                            dateOfBirth = new DateTime(1890, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Book_Store.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("imgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("publicationDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Genre = "Technology",
                            Price = 0.0,
                            Title = "C# Programming Basics",
                            imgUrl = "",
                            publicationDate = new DateOnly(2020, 1, 1)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Genre = "Technology",
                            Price = 0.0,
                            Title = "Advanced C# Techniques",
                            imgUrl = "",
                            publicationDate = new DateOnly(2021, 2, 15)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            Genre = "Technology",
                            Price = 0.0,
                            Title = "Learning Python",
                            imgUrl = "",
                            publicationDate = new DateOnly(2019, 3, 20)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            Genre = "Technology",
                            Price = 0.0,
                            Title = "Mastering Python",
                            imgUrl = "",
                            publicationDate = new DateOnly(2018, 4, 5)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 1,
                            Genre = "Technology",
                            Price = 0.0,
                            Title = "Java for Beginners",
                            imgUrl = "",
                            publicationDate = new DateOnly(2017, 5, 10)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 2,
                            Genre = "Technology",
                            Price = 0.0,
                            Title = "Advanced Java Concepts",
                            imgUrl = "",
                            publicationDate = new DateOnly(2016, 6, 15)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 1,
                            Genre = "Technology",
                            Price = 0.0,
                            Title = "JavaScript Essentials",
                            imgUrl = "",
                            publicationDate = new DateOnly(2020, 7, 20)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 2,
                            Genre = "Technology",
                            Price = 0.0,
                            Title = "React.js Guide",
                            imgUrl = "",
                            publicationDate = new DateOnly(2021, 8, 25)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 1,
                            Genre = "Technology",
                            Price = 0.0,
                            Title = "Vue.js in Action",
                            imgUrl = "",
                            publicationDate = new DateOnly(2019, 9, 30)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 2,
                            Genre = "Technology",
                            Price = 0.0,
                            Title = "Angular for Professionals",
                            imgUrl = "",
                            publicationDate = new DateOnly(2018, 10, 5)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 1,
                            Genre = "Technology",
                            Price = 0.0,
                            Title = "Machine Learning with Python",
                            imgUrl = "",
                            publicationDate = new DateOnly(2017, 11, 10)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 2,
                            Genre = "Technology",
                            Price = 0.0,
                            Title = "Deep Learning Techniques",
                            imgUrl = "",
                            publicationDate = new DateOnly(2016, 12, 15)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 1,
                            Genre = "Technology",
                            Price = 0.0,
                            Title = "Data Science Essentials",
                            imgUrl = "",
                            publicationDate = new DateOnly(2020, 1, 20)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 2,
                            Genre = "Technology",
                            Price = 0.0,
                            Title = "Big Data Analytics",
                            imgUrl = "",
                            publicationDate = new DateOnly(2021, 2, 25)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 1,
                            Genre = "Technology",
                            Price = 0.0,
                            Title = "Cloud Computing Basics",
                            imgUrl = "",
                            publicationDate = new DateOnly(2019, 3, 30)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 2,
                            Genre = "Technology",
                            Price = 0.0,
                            Title = "AWS for Beginners",
                            imgUrl = "",
                            publicationDate = new DateOnly(2018, 4, 5)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 1,
                            Genre = "Technology",
                            Price = 0.0,
                            Title = "Azure in Action",
                            imgUrl = "",
                            publicationDate = new DateOnly(2017, 5, 10)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 2,
                            Genre = "Technology",
                            Price = 0.0,
                            Title = "GCP Fundamentals",
                            imgUrl = "",
                            publicationDate = new DateOnly(2016, 6, 15)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 1,
                            Genre = "Technology",
                            Price = 0.0,
                            Title = "Kubernetes Guide",
                            imgUrl = "",
                            publicationDate = new DateOnly(2020, 7, 20)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 2,
                            Genre = "Technology",
                            Price = 0.0,
                            Title = "Docker Deep Dive",
                            imgUrl = "",
                            publicationDate = new DateOnly(2021, 8, 25)
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 1,
                            Genre = "Technology",
                            Price = 0.0,
                            Title = "Microservices Architecture",
                            imgUrl = "",
                            publicationDate = new DateOnly(2019, 9, 30)
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 2,
                            Genre = "Technology",
                            Price = 0.0,
                            Title = "DevOps Essentials",
                            imgUrl = "",
                            publicationDate = new DateOnly(2018, 10, 5)
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 1,
                            Genre = "Technology",
                            Price = 0.0,
                            Title = "Agile Development",
                            imgUrl = "",
                            publicationDate = new DateOnly(2017, 11, 10)
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 2,
                            Genre = "Technology",
                            Price = 0.0,
                            Title = "Scrum Master Guide",
                            imgUrl = "",
                            publicationDate = new DateOnly(2016, 12, 15)
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 1,
                            Genre = "Business",
                            Price = 0.0,
                            Title = "Project Management Basics",
                            imgUrl = "",
                            publicationDate = new DateOnly(2020, 1, 20)
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 2,
                            Genre = "Business",
                            Price = 0.0,
                            Title = "Leadership Skills",
                            imgUrl = "",
                            publicationDate = new DateOnly(2021, 2, 25)
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 1,
                            Genre = "Business",
                            Price = 0.0,
                            Title = "Effective Communication",
                            imgUrl = "",
                            publicationDate = new DateOnly(2019, 3, 30)
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 2,
                            Genre = "Business",
                            Price = 0.0,
                            Title = "Negotiation Techniques",
                            imgUrl = "",
                            publicationDate = new DateOnly(2018, 4, 5)
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 1,
                            Genre = "Business",
                            Price = 0.0,
                            Title = "Time Management",
                            imgUrl = "",
                            publicationDate = new DateOnly(2017, 5, 10)
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 2,
                            Genre = "Business",
                            Price = 0.0,
                            Title = "Financial Analysis",
                            imgUrl = "",
                            publicationDate = new DateOnly(2016, 6, 15)
                        },
                        new
                        {
                            Id = 31,
                            AuthorId = 1,
                            Genre = "Finance",
                            Price = 0.0,
                            Title = "Investing 101",
                            imgUrl = "",
                            publicationDate = new DateOnly(2020, 7, 20)
                        },
                        new
                        {
                            Id = 32,
                            AuthorId = 2,
                            Genre = "Finance",
                            Price = 0.0,
                            Title = "Stock Market Basics",
                            imgUrl = "",
                            publicationDate = new DateOnly(2021, 8, 25)
                        },
                        new
                        {
                            Id = 33,
                            AuthorId = 1,
                            Genre = "Finance",
                            Price = 0.0,
                            Title = "Real Estate Investment",
                            imgUrl = "",
                            publicationDate = new DateOnly(2019, 9, 30)
                        },
                        new
                        {
                            Id = 34,
                            AuthorId = 2,
                            Genre = "Finance",
                            Price = 0.0,
                            Title = "Personal Finance Management",
                            imgUrl = "",
                            publicationDate = new DateOnly(2018, 10, 5)
                        },
                        new
                        {
                            Id = 35,
                            AuthorId = 1,
                            Genre = "Finance",
                            Price = 0.0,
                            Title = "Retirement Planning",
                            imgUrl = "",
                            publicationDate = new DateOnly(2017, 11, 10)
                        },
                        new
                        {
                            Id = 36,
                            AuthorId = 2,
                            Genre = "Finance",
                            Price = 0.0,
                            Title = "Insurance Essentials",
                            imgUrl = "",
                            publicationDate = new DateOnly(2016, 12, 15)
                        },
                        new
                        {
                            Id = 37,
                            AuthorId = 1,
                            Genre = "Health",
                            Price = 0.0,
                            Title = "Health and Wellness",
                            imgUrl = "",
                            publicationDate = new DateOnly(2020, 1, 20)
                        },
                        new
                        {
                            Id = 38,
                            AuthorId = 2,
                            Genre = "Health",
                            Price = 0.0,
                            Title = "Nutrition Basics",
                            imgUrl = "",
                            publicationDate = new DateOnly(2021, 2, 25)
                        });
                });

            modelBuilder.Entity("Book_Store.Models.Book", b =>
                {
                    b.HasOne("Book_Store.Models.Author", "Author")
                        .WithMany("books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Book_Store.Models.Author", b =>
                {
                    b.Navigation("books");
                });
#pragma warning restore 612, 618
        }
    }
}
